name: Container
on: push

jobs:
    node-docker:
        runs-on: ubuntu-latest
        container: node:20-alpine3.16
        steps:
            - name: Log node version
              run: |
                ndoe -v
                cat /eyc/os-release